#!/bin/bash
# PythonAnywhere 部署腳本
# 請按照 README.md 中的步驟操作

echo "PythonAnywhere 部署說明："
echo ""
echo "1. 註冊免費賬戶: https://www.pythonanywhere.com/registration/"
echo "   - 使用 GitHub 登錄（不需要信用卡）"
echo ""
echo "2. 上傳代碼到 PythonAnywhere:"
echo "   方法 A: 使用 git clone"
echo "   git clone https://github.com/chanpuirider-design/szcb-market-api.git"
echo ""
echo "   方法 B: 使用控制台上傳 ZIP"
echo "   https://github.com/chanpuirider-design/szcb-market-api/archive/refs/heads/main.zip"
echo ""
echo "3. 配置 Web App:"
echo "   - 進入 Web 頁面"
echo "   - 選擇 'Manual Config'"
echo "   - Python 版本: 3.11"
echo "   - 工作目錄: /home/YOUR_USERNAME/szcb-market-api"
echo "   - 虛擬環境: 創建新的"
echo ""
echo "4. 安裝依賴:"
echo "   pip install -r requirements.txt"
echo ""
echo "5. 配置 WSGI 文件:"
echo "   編輯 /home/YOUR_USERNAME/szcb-market-api/wsgi.py"
echo ""
echo "6. 重啟 Web App"
echo ""
echo "詳細說明請查看 README.md"
